[package]
name = "network_visu"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.25.0"
egui = { version = "0.25.0", features = ["serde"] }
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
